/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    borderRadius: {
      none: "0",
      sm: "10px",
      DEFAULT: "14px",
      md: "14px",
      lg: "16px",
      xl: "16px",
      "2xl": "18px",
      "3xl": "20px",
      full: "9999px",
    },
    extend: {
      fontFamily: {
        sans: [
          '"Space Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
        mono: [
          '"Space Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace",
        ],
        pixel: ['"Press Start 2P"', "cursive"],
        display: ['"Press Start 2P"', "cursive"],
      },
      colors: {
        appBg: "#F5F2E8",
        surfaceLight: "#EFEADB",
        surfaceGray: "#E8E2D4",
        primaryDark: "#121212",
        primaryMid: "#1A1A1A",
        primaryLight: "#2A2A2A",
        accentGreen: "#D4FF37",
        accentSage: "#A8C94A",
        accentLavender: "#D3C3FC",
        accentPink: "#FFC1CC",
        accentYellow: "#FFF1A8",
        accentCyan: "#B0E0E6",
        successBg: "#EAF8C4",
        successText: "#1A1A1A",
        textPrimary: "#121212",
        textSecondary: "#5C584E",
        border: "#121212",
      },
      boxShadow: {
        soft: "none",
        card: "none",
        pill: "none",
        sm: "none",
        DEFAULT: "none",
        md: "none",
        lg: "none",
        xl: "none",
        "2xl": "none",
        inner: "none",
        none: "none",
      },
      backgroundImage: {
        "gradient-green-card":
          "linear-gradient(135deg, #121212 0%, #1A1A1A 55%, #2A2A2A 100%)",
        "gradient-brand-card":
          "linear-gradient(135deg, #121212 0%, #1A1A1A 55%, #2A2A2A 100%)",
      },
    },
  },
  plugins: [],
};
